import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`bg-green-950 ${geistSans.variable} ${geistMono.variable} antialiased pb-[200px]`}
      >
        <nav className="bg-green-900 p-3 shadow shadow-slate-900 ">NAV HEADER</nav>
        
        
          {children}
        
      </body>
    </html>
  );
}
